services:
  ld_telegram_downloader:
    image: ld_telegram_downloader:3.0
    build: .
    container_name: tgdownloader_aitrans
    ports:
      - "5000:5000"
    #environment:
    #  - http_proxy=http://192.168.101.30:10811
    #  - https_proxy=http://192.168.101.30:10811
    volumes:
      - "./downloads:/app/downloads"

      # Rclone
      - "$HOME/.config/rclone/:$HOME/.config/rclone/"

      - "./config.yaml:/app/config.yaml"
      - "./data.yaml:/app/data.yaml"
      - "./log/:/app/log/"
      - "./sessions/:/app/sessions/"
      - "./temp/:/app/temp/"
      - "./configs/:/app/configs/"
      - "./accounts.yaml:/app/accounts.yaml"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
    #restart: "unless-stopped"
