services:
  ld_telegram_downloader:
    image: leduchuong/ld_tg_downloader:3.2
    build: .
    container_name: ld_tg_downloader
    ports:
      - "5000:5000"
    volumes:
      - "./downloads:/app/downloads"
      - "./config.yaml:/app/config.yaml"
      - "./accounts.yaml:/app/accounts.yaml"
      - "./data.yaml:/app/data.yaml"
      - "./configs:/app/configs"
      - "./sessions:/app/sessions"
      - "./temp:/app/temp"
      - "./log:/app/log"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
    restart: "unless-stopped"
